name: go_uma
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sp_util: 2.0.3
  carousel_slider: 4.1.1
  google_maps_flutter: 2.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

